Feat/main page mobile
VladLi742/aviasales-demo-frontend pull request #2
Opened 2018-02-17 08:49 UTC by VladLi742

2018-02-17 17:37 UTC, evgenyrodionov commented
https://codesandbox.io/s/github/VladLi742/aviasales-demo-frontend/tree/feat%2Fmain-page-mobile
![image](https://user-images.githubusercontent.com/775692/36343846-552302c4-1422-11e8-8c5a-86498123e77c.png)

2018-02-17 17:45 UTC, imevro requested changes

2018-02-17 17:45 UTC, evgenyrodionov commented on package.json
> +  "name": "main-page-mobile",
??

2018-02-17 17:45 UTC, evgenyrodionov commented on public/index.html
> +  <title>React App</title>
смени

2018-02-17 17:45 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
опять же

2018-02-17 17:45 UTC, evgenyrodionov commented on src/App.css
> +.App-logo {
мусор

2018-02-17 17:45 UTC, evgenyrodionov commented on src/App.css
> +  box-sizing: border-box;
неправильно

https://www.paulirish.com/2012/box-sizing-border-box-ftw/

2018-02-17 17:45 UTC, evgenyrodionov commented on src/App.js
> +import reactFlexboxGrid, { Row, Col } from "react-flexbox-grid";
что за reactFlexboxGrid и зачем он нужен, если ты его не используешь?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/App.js
> +import normalize from "normalize.css";
цсс не так импортится

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Articles/index.js
> +import articleList from "./article-list.js";
ты и так в Articles, зачем ты префиксуешь файлы слово article?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/BestPrices/Direction.js
> +  @media (min-width: 768px) and (max-width: 992px) {
мы не используем max-width

2018-02-17 17:45 UTC, evgenyrodionov commented on src/BestPrices/Direction.js
> +  @media (min-width: 768px) and (max-width: 992px) {
в медиакверис

2018-02-17 17:45 UTC, evgenyrodionov commented on src/BestPrices/images/flag-md.svg
> +<image id="image0" width="60" height="60" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAAAXNSR0IArs4c6QAACf5JREFUaAXtWUtsG9cVPUPODH+SSEok
это же пнг, почему оно в свг?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/BestPrices/kishinev-list.js
> +    price: "16 277 ₽"
храни числом

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Footer/AdditionalInfo.js
> +  height: 42px;
![image](https://user-images.githubusercontent.com/775692/36343882-28d60f44-1423-11e8-9011-b1b5f21248d7.png)

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Footer/AdditionalInfo.js
> +        </List>
если это список, почему в нём только один элемент?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Footer/Links.js
> +const Links = styled.li`
почему единичный элемент списка обозначается как будто это список ссылок во множ числе?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Footer/Links.js
> +            {link.links.map((link, index) => {
link.links? wtf?

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Footer/index.js
> +export default function() {
ставь переносы между блоками кода

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Header/index.js
> +      font-family: Roboto;
что тут стало с кодстайлом

2018-02-17 17:45 UTC, evgenyrodionov commented on src/Header/index.js
> +  &:nth-last-child(2) > :first-child {
отвратительные неподдерживаемые селекторы. как с этим работать другому человеку?

2018-02-17 21:02 UTC, VladLi742 commented on src/BestPrices/kishinev-list.js
> +    price: "16 277 ₽"
id хранить числом? Это как?

2018-02-17 21:04 UTC, VladLi742 commented on package.json
> +  "name": "main-page-mobile",
Когда создавал ветку думал, что буду пушить сюда только для mobile версии правки. Но не сложилось.

2018-02-17 21:05 UTC, VladLi742 commented on public/index.html
> +  <title>React App</title>
Поменял.

2018-02-17 21:05 UTC, VladLi742 commented on public/manifest.json
> +  "short_name": "React App",
Поменял.

2018-02-17 21:06 UTC, VladLi742 commented on src/App.css
> +.App-logo {
Удалил сам файл.

2018-02-17 21:06 UTC, VladLi742 commented on src/App.css
> +  box-sizing: border-box;
Понял. Сам файл уже удалил.

2018-02-17 21:07 UTC, evgenyrodionov commented
ты блядь мне всю почту засрал, перестань комментировать пуллреквест

2018-02-17 21:09 UTC, VladLi742 commented on src/App.js
> +import reactFlexboxGrid, { Row, Col } from "react-flexbox-grid";
Я копировал его с некоторых компонентов, когда создавал новые. А ещё я изначально думал, что сетку буду действительно везде использовать).
Убрал там, где он не используется.

2018-02-17 21:09 UTC, VladLi742 commented on src/App.js
> +import normalize from "normalize.css";
Понял. Исправил.

2018-02-17 21:12 UTC, VladLi742 commented on src/Articles/index.js
> +import articleList from "./article-list.js";
Думал, будет не так понятно для читающего. Исправил.

2018-02-17 21:13 UTC, VladLi742 commented on src/BestPrices/Direction.js
> +  @media (min-width: 768px) and (max-width: 992px) {
Понял. Везде поменял.

2018-02-17 21:13 UTC, VladLi742 commented on src/BestPrices/images/flag-md.svg
> +<image id="image0" width="60" height="60" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAAAXNSR0IArs4c6QAACf5JREFUaAXtWUtsG9cVPUPODH+SSEok
Я почему-то просмотрел этот момент. Исправил все svg на png.

2018-02-17 21:18 UTC, VladLi742 commented on src/Footer/AdditionalInfo.js
> +  height: 42px;
Исправил. Потихоньку исправляю, то что написал до.

2018-02-17 21:28 UTC, VladLi742 commented on src/Footer/Links.js
> +const Links = styled.li`
Не обратил на это внимание. Поменял.

2018-02-17 21:29 UTC, VladLi742 commented on src/Footer/AdditionalInfo.js
> +        </List>
Не обратил внимание на название. По сути это обёртка, контейлер для ссылки. Поменял на LinkWrapper т.к. по-другому не знаю как назвать.

2018-02-17 21:32 UTC, VladLi742 commented on src/Footer/Links.js
> +            {link.links.map((link, index) => {
Не мог придумать получше.
Поменял на link.titles.

2018-02-17 21:32 UTC, VladLi742 commented on src/Footer/index.js
> +export default function() {
Понял.

2018-02-17 21:34 UTC, VladLi742 commented on src/Header/index.js
> +      font-family: Roboto;
Иногда я пропускаю подобные моменты, иногда prettier не делает как надо(с media query он у меня так делает постоянно). Так что это случайность.

2018-02-17 21:37 UTC, VladLi742 commented
Ок, извини. Думал, на них нужно отвечать.

2018-02-18 0:07 GMT+03:00 Evgeny Rodionov <notifications@github.com>:

> ты блядь мне всю почту засрал, перестань комментировать пуллреквест
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/VladLi742/aviasales-demo-frontend/pull/2#issuecomment-366471442>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AdgUvVNCmjYTZxpqZBlooDPuisXid7lyks5tVz98gaJpZM4SJPlj>
> .
>

2018-02-18 22:41 UTC, VladLi742 commented
По поводу футера была проблема с flex-ом и я её решил:
 ![2018-02-19_01-03-03](https://user-images.githubusercontent.com/30938301/36357545-a98e3358-1510-11e8-8225-a554d2f90c69.png)

2018-02-19 16:58 UTC, imevro approved these changes

2018-02-19 16:58 UTC, merged